### ISSUE TITLE
command not found error

### ISSUE THREAD

**Issue by Jaehyuk-Lee** [MaikoTan/cactbot-highlight#3]
![K-002](https://user-images.githubusercontent.com/4695371/95807790-fb99d780-0d45-11eb-8cbf-c337078017e4.png)
Error from command 'Translate Timeline To ...' (command 'cactbot.timeline.translateTimeline' not found) occured

I use market place version, v0.1.0
Just in case, I have tried remove - restart - install - restart - test command.
This happened on every timeline text file.

my `settings.json`
```
{
    "files.associations": {
        "*.txt": "cactbot-timeline"
    },
    "cactbot.timeline.defaultLocale": "ko",
}
```

Even though I removed `"cactbot.timeline.defaultLocale": "ko",` this happens again.

**Comment by MaikoTan** [comment]
I have never seen this bug before...

Can you open up `Help > Toggle Developer Tools`, and do it again, see what is output in the console?

**Comment by Jaehyuk-Lee** [comment]
```
'MaikoTan.cactbot-highlight' 확장을 활성화하지 못했습니다. Cannot find module 'vm2'
Require stack:
- c:\Users\재혁\.vscode\extensions\maikotan.cactbot-highlight-0.1.0\out\translateTimeline.js
- c:\Users\재혁\.vscode\extensions\maikotan.cactbot-highlight-0.1.0\out\extension.js
- c:\Program Files\Microsoft VS Code\resources\app\out\vs\loader.js
- c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-amd.js
- c:\Program Files\Microsoft VS Code\resources\app\out\bootstrap-fork.js.
```

`'MaikoTan.cactbot-highlight' 확장을 활성화하지 못했습니다.` is "Could not enable 'MaikoTan.cactbot-highlight' extension."

**Comment by MaikoTan** [comment]
Ah, I see. It seems like I have not bundled the dependency `vm2` in the market place version. Sorry!

**Comment by MaikoTan** [comment]
@Jaehyuk-Lee I have release a new version, see if this bug has fixed?

**Comment by Jaehyuk-Lee** [comment]
yes, it's fixed 😄
