### ISSUE TITLE
Bug: Translate Current Timeline not working

### ISSUE THREAD

**Issue by Bing-su** [MaikoTan/cactbot-highlight#488]
Cactbot Highlight version v0.6.2

[Code_sO7xue3cTl.webm](https://github.com/user-attachments/assets/c33fe478-2375-4dc7-94dc-7daaa408f210)

In vscode output, it doesn't seem to generate any output.

**Comment by Jaehyuk-Lee** [comment]
Same here 😅

**Comment by MaikoTan** [comment]
Duplicated with #483

**Comment by MaikoTan** [comment]
Should be resolved in v0.6.3.
